"""empty message

Revision ID: 8801c7410f36
Revises: 005973730a30
Create Date: 2018-09-29 17:31:07.369250

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '8801c7410f36'
down_revision = '005973730a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sequence')
    # ### end Alembic commands ###
